name: Build, Package, Release (main)
'on':
  release:
    types:
      - created
  push:
    branches:
      - main
env:
  VERSION: null
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.MO_REGISTRY_AUTH_URL__MAIN }}
          username: ${{ vars.MO_REGISTRY_USER__MAIN }}
          password: ${{ secrets.MO_REGISTRY_PAT__MAIN }}
      - id: releaseWithMogenius-d92c3b1d4ddf6006c1b3
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: false
          image: ${{ vars.MO_IMAGE_NAME__MAIN }}:${{ env.VERSION }}
          kind: Deployment
          namespace: keycloak
          resourceName: nginx
          containerName: nginx
          keyKind: ${{ vars.MO_API_KIND__MAIN }}
          token: ${{ secrets.MO_API_TOKEN__d92c3b1d4ddf6006c1b3__MAIN }}
