name: Build, Package, Release (main)
'on':
  release:
    types:
      - created
  push:
    branches:
      - main
env:
  VERSION: null
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.MO_REGISTRY_AUTH_URL__MAIN }}
          username: ${{ vars.MO_REGISTRY_USER__MAIN }}
          password: ${{ secrets.MO_REGISTRY_PAT__MAIN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ${{ vars.MO_DOCKERCONTEXT__MAIN }}
          file: ${{ vars.MO_DOCKERFILE__MAIN }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.MO_IMAGE_NAME__MAIN }}:${{ env.VERSION }}
            ${{ vars.MO_IMAGE_NAME__MAIN }}:latest
          build-args: ''
      - id: releaseWithMogenius-d92c3b1d4ddf6006c1b3
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: false
          image: ${{ vars.MO_IMAGE_NAME__MAIN }}:${{ env.VERSION }}
          kind: Deployment
          namespace: keycloak
          resourceName: nginx
          containerName: nginx
          keyKind: ${{ vars.MO_API_KIND__MAIN }}
          token: ${{ secrets.MO_API_TOKEN__d92c3b1d4ddf6006c1b3__MAIN }}
      - id: releaseWithMogenius-63FF515A77B8B12D3273
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: false
          image: ${{ vars.MO_REGISTRY_URL__MAIN }}/${{ vars.MO_IMAGE_NAME__MAIN }}:${{ env.VERSION }}
          kind: Deployment
          namespace: gitea
          resourceName: nginx2
          containerName: nginx2
          keyKind: ${{ vars.MO_API_KIND__MAIN }}
          token: ${{ secrets.MO_API_TOKEN__63FF515A77B8B12D3273__MAIN }}
